title: "Firstname Lastname"
tagline: "Speech & Audio ML Researcher"
description: "Short abstract: I build reliable perceptual evaluation methods for speech systems, diffusion-map embeddings, and non-asymptotic guarantees."
# Replace USERNAME below with your GitHub username
url: "https://USERNAME.github.io"
baseurl: ""
author:
  name: "Firstname Lastname"
  email: you@example.com
  avatar: /assets/img/profile.jpg
social:
  twitter: yourhandle
  github: USERNAME
  scholar: "https://scholar.google.com/citations?user=XXXXXXXXXXX"
  linkedin: "https://www.linkedin.com/in/yourprofile/"
google_analytics: ""   # e.g., G-XXXXXXX (optional)
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
theme: null
plugins: []
# Navigation labels
nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Code
    url: /code/
  - title: Blog
    url: /blog/
  - title: CV
    url: /cv/
