title: Your Name
tagline: Postdoctoral Researcher — Speech, Audio & ML
description: Research in speech, audio perception, diffusion maps, and machine learning. Clean, simple, and up-to-date.
baseurl: ""   # leave empty for user.github.io; set to "/project-name" for project pages
url: "https://your-username.github.io"
email: you@university.edu
github_username: your-github
google_scholar: https://scholar.google.com/citations?user=YOURID
orcid: https://orcid.org/0000-0000-0000-0000
linkedin: https://www.linkedin.com/in/your-linkedin/
twitter: https://x.com/your-handle

permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Your Name
      toc: false
      comments: false