title: "Amir Ivry"
tagline: ""  # optional; shows under your name if non-empty
description: ""
url: "https://amir-ivry.github.io"
baseurl: ""
author:
  name: "Amir Ivry"
  email: "aivry@ieee.org"
  avatar: "/assets/img/Amir Profile Pic.jpg"

social:
  github: "Amir-Ivry"
  scholar: "https://scholar.google.com/citations?user=rQCVwksAAAAJ&hl=en&oi=ao"
  linkedin: "https://www.linkedin.com/in/amirivry/"

markdown: kramdown
kramdown: { input: GFM }
theme: null
plugins: []
permalink: /blog/:year/:month/:day/:title/

nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Code
    url: /code/
  - title: Blog
    url: /blog/
  - title: CV
    url: /cv/
